### ISSUE TITLE
Possible to cache DB?

### ISSUE THREAD

**Issue by wwood** [motu-tool/mOTUs#100]
Hi,

I'm attempting to benchmark some different profilers, and as part of this, I'm copying the database (and reads) to local disk, so that the processes are less IO-bound and so there is less noise in the benchmark from random happenings of others on the HPC.

Is there a way to specify where the DB mOTUs should use is? Also, I was too lazy to look at the code - where does downloadDB actually put the download, so I know what to copy? I'm using a conda install if that helps.

Thanks, ben

**Comment by AlessioMilanese** [comment]
Hi Ben,

> Is there a way to specify where the DB mOTUs should use is? 

You can use the `-db` command to specify the directory.

> where does downloadDB actually put the download, so I know what to copy?

mOTUs is installed as a python package into one of the `site-packages` folders - The exact location depends on the exact `pip` command. The database is in the subfolder of the mOTUs package folder.

Here is the command to find the location of the `site-packages`

```
python -m site
```

**Comment by wwood** [comment]
Excellent, thanks.


-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
