### ISSUE TITLE
is mOTUs suitable for Metatranscriptome sequence?

### ISSUE THREAD

**Issue by zhaoxvwahaha** [motu-tool/mOTUs#104]
Can I use mOTUs to identify microbiome in Metatranscriptome sequence? And does mOTUs already include binning process? Do I still need binning after get the mOTUs results?

**Comment by AlessioMilanese** [comment]
Hi @zhaoxvwahaha,

> Can I use mOTUs to identify microbiome in Metatranscriptome sequence?

You can use mOTUs to do taxonomic profiling of metatranscriptome samples. In other words you can use mOTUs to identify which species are present and their relative abundance. In our paper we showed that mOTUs is well suited to do this, compared to other tools: https://www.nature.com/articles/s41467-019-08844-4/figures/4

> And does mOTUs already include binning process?

No. The input for mOTUs is one or multiple fastq files.

> Do I still need binning after get the mOTUs results?

No, mOTUs will map your reads to a big set of known and unknown species. As a result you will know which known and unknown species are present in your sample.
What you can do, is to create metagenome assembled genomes (MAGs) yourself and extend the mOTUs database to be able to profile additional species that might be missing in the mOTUs database. See: https://github.com/motu-tool/mOTUs-extender
