### ISSUE TITLE
no abundance

### ISSUE THREAD

**Issue by ucassee** [motu-tool/mOTUs#106]
Hi,

I use the following command to run mOTUs, but it seems that no reads are mapped to the reference database.

`motus profile -s ANT29P4-06_1.fastq -n ANT29P4-06  -t 40 -q -o ANT29P4-06_taxonomy_profile.txt`

My sample is from Antarctic Pole. The length of my reads is 150bp. I attached the output file. I was wondering whether this result is normal.
[ANT29P4-06_taxonomy_profile.txt](https://github.com/motu-tool/mOTUs/files/10097526/ANT29P4-06_taxonomy_profile.txt)

Thanks,

**Comment by AlessioMilanese** [comment]
Hi,

You can see with the command:
```
cat ANT29P4-06_taxonomy_profile.txt | grep -v "0.0000000000"
```

the species that are not zero. You have 52 ref-mOTUs, 1 meta-mOTU and 56 ext-mOTUs, plus the `unassigned`.

**Comment by AlessioMilanese** [comment]
Nice! Thanks for your interest in mOTUs.
Let us know if everything works out.
