### ISSUE TITLE
Genome size normalization

### ISSUE THREAD

**Issue by ramanujamr** [motu-tool/mOTUs#108]
Hi
Firstly, thank you for developing this excellent tool.
I am testing this on some datasets and wanted to know if the final relative abundances are normalized by genome size.

**Comment by shenwei356** [comment]
mOTUs are a marker-gene-based profiling tool, which should no need to normalize the abundance by genome size.

**Comment by AlessioMilanese** [comment]
Thank you for your message and your interest in mOTUs.

mOTUs is based on 10 universal single copy marker genes. These marker genes are present in a single copy in all genomes, regardless of their size. As a result, the final relative abundance is not influenced by the size or complexity of the genomes involved, and can be considered to be normalized by genome size.

you can see an example in Supplementary Figure 1 of the mOTUs2 paper:
https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-019-08844-4/MediaObjects/41467_2019_8844_MOESM1_ESM.pdf

**Comment by ramanujamr** [comment]
Thank you! I appreciate the detailed clarification.
