### ISSUE TITLE
zipped input files

### ISSUE THREAD

**Issue by CosteaPaul** [motu-tool/mOTUs#110]
This should support fastq.gz input files :).

**Comment by CosteaPaul** [comment]
On the latest version:

motus profile -s someFile_S1_L001_R1_001.fastq.gz 

2023-02-17 14:49:09 Map reads to the marker gene database
   Reads are aligned (by BWA) to marker gene sequences in the reference database
   Reads are filtered for:
    - similarity to the reference gene (>97%), and
    - length of the alignment (at least 75 nucleotides, -l option)
   
   Number of detected lanes: 1

   2023-02-17 14:49:09 Run bwa on lane 1

Error: file someFile_S1_L001_R1_001.fastq.gz is not a fastq file

Unzipping and running works fine...

**Comment by CosteaPaul** [comment]
Never mind. This was on me.
Seems my gpfs takes a while to sync properly.

I owe you a beer for jumping the gun :).

**Comment by AlessioMilanese** [comment]
Sounds good 🍺 :)
