### ISSUE TITLE
Strange inconsistant row in mOTUs output

### ISSUE THREAD

**Issue by xapple** [motu-tool/mOTUs#112]
I ran the following command, with some artificially simulated HiSeq paired-end reads:

    $ ~/mambaforge/envs/tax/bin/motus profile -c -p -u -n count -t 10 -o ~/runs/iss/motus.tsv -f ~/runs/iss/reads_fwd.fastq -r ~/runs/iss/reads_rev.fastq

And when I look at the output TSV file, the last line seems like a bug. Here is the tail of the file `motus.tsv`:

    meta_mOTU_v25_14519     Proteobacteria species incertae sedis   NA      0
    meta_mOTU_v25_14520     Gammaproteobacteria species incertae sedis      NA      0
    meta_mOTU_v25_14521     Bacteria species incertae sedis NA      0
    meta_mOTU_v25_14522     Clostridiales species incertae sedis    NA      0
    meta_mOTU_v25_14523     Bacteria species incertae sedis NA      0
    -1      -1      NA      56

Should we just deleted the last line in this case ? Is it safe to ignore ?

**Comment by hjruscheweyh** [comment]
Good Morning @xapple


We would encourage you to switch to a more recent version as 2.5 is based on data from 2019. Version 3 includes data from MAGs from 23 environments --> https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-022-01410-z


The -1 (in version 3 it is called unassigned) represents the abundance of unknown species. This fraction is important to normalise e.g the relative the abundance within a sample but also to compare multiple samples with another (see Figure 2 in https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.218 and Figure 1 in the https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-022-01410-z).  So no, don't remove it.

Best,
Hans
