### ISSUE TITLE
ImportError: No module named motus.motus

### ISSUE THREAD

**Issue by snehamurthy21** [motu-tool/mOTUs#113]
I installed motus using conda and activated the environment,
could u pls help me resolve this error I am getting when i run "motus profile --test"

Traceback (most recent call last):
  File "/home/sneha/.local/bin/motus", line 5, in <module>
    from motus.motus import main
ImportError: No module named motus.motus

**Comment by hjruscheweyh** [comment]
Hello @snehamurthy21 

It looks like your installation has failed. Can you share the version of motus that you have installed together with the conda command or the `conda.yaml` file?

Best,
hans

**Comment by snehamurthy21** [comment]
Hello

Thank you for your reply. 2 different installation methods were clashing together half installed. I fixed it.
Will close the issue.

Regards,
sneha
