### ISSUE TITLE
Compatibility between 2.5 and 3.0 mOTUs.

### ISSUE THREAD

**Issue by ChanyeongKim** [motu-tool/mOTUs#114]
Hi, thanks always for providing the nice tool.

I have a question about the mOTUs mapping between v2.5 and v3.0.
From the mOTUs v3.0 paper, It seemed that the `ref_mOTUs` and `meta_mOTUs` are just inherited from the v2.5.
Then, does it mean that the two mOTUs from v2.5 and v3 with the same index are identical?
Can I consider both `ref_mOTU_v25_00001` and `ref_mOTU_v3_00001` representing the identical OTU?

Thanks a lot.

**Comment by hjruscheweyh** [comment]
Hello @ChanyeongKim 

The numerical identifiers have not changed but we have extended the database massively in v3 (and v3.1) and some marker genes/genomes have been removed.  

best,
Hans
