### ISSUE TITLE
Incompatible with new versions of samtools?

### ISSUE THREAD

**Issue by Ge0rges** [motu-tool/mOTUs#115]
Hello,

I was wondering if the dependency requirements could be bumped to use more recent versions of `htslib` implementing recent bug fixes.

Thank you

**Comment by hjruscheweyh** [comment]
Hello @Ge0rges 

mOTUs is using samtools only for reading/writing/sorting bam files and not editing. The used functions should be relatively stable in htslib/samtools releases. So yes, using a newer version of samtools should not create any issue.  However we cannot test this at the moment.

Best,
Hans
