### ISSUE TITLE
Update to use GTDB 214

### ISSUE THREAD

**Issue by Ge0rges** [motu-tool/mOTUs#116]
Hello,

I was wondering if there's a timeline for the release of a version of mOTU making use of GTDB release 214.

Thanks

**Comment by hjruscheweyh** [comment]
Hello @Ge0rges 

There is currently no plan to update the GTDB taxonomy of all 700K genomes. You could, however, download the the ~30k representative genomes using the https://github.com/motu-tool/motus_v3_genomes  tool and run them through GTDBtk R214 without too much computational overhead.

Best,
hans
