### ISSUE TITLE
Count table output? 

### ISSUE THREAD

**Issue by ayabrown** [motu-tool/mOTUs#117]
Hi, I was wondering why the '-c' option (or similar) for count table is no longer available in v3.0. 

I was able to get the intermediate count table (of each MG) in v3.0 when running with '-M' option but not a per-taxa one.  

any help would be much appreciated, 

Aya

**Comment by hjruscheweyh** [comment]
Hello @ayabrown 

The -c option is still part of the mOTUs pipeline. When running profile with -M you will also create the MGC file which also produces the markergenecluster abundances (not the taxa, but of individual markegeneclusters inside a taxa). This MGC file is only an intermediate file that is produced to avoid re-parsing of big BAM files. The mOTUs file (-o) should have the abundances as counts when you specify the -c parameter.

Best,
hans

**Comment by ayabrown** [comment]
got it! Thank you so much!
