### ISSUE TITLE
Update GTDB taxonomy

### ISSUE THREAD

**Issue by ericvdtoorn** [motu-tool/mOTUs#120]
The taxonomy released on the wiki is for version 3.0.0: https://github.com/motu-tool/mOTUs/wiki/GTDB-taxonomy-for-the-mOTUs

Would it be possible to update it?

**Comment by hjruscheweyh** [comment]
Hello @ericvdtoorn 

There is a link between genomes and their associated mOTU on Zenodo --> [https://zenodo.org/records/10275750](https://zenodo.org/records/10275750).
