### ISSUE TITLE
profile output looks wired

### ISSUE THREAD

**Issue by raytaoliu** [motu-tool/mOTUs#122]
Hi,
I am processing my whole genomic sequencing files with motus, but my output seems very strange, the following are part of my output:
# git tag version 3.1.0 |  motus version 3.1.0 | map_tax 3.1.0 | gene database: nr3.1.0 | calc_mgc 3.1.0 -y insert.scaled_counts -l 75 | calc_motu 3.1.0 -k mOTU -C no_CAMI -g 3 | taxonomy: ref_mOTU_3.1.0 meta_mOTU_3.1.0
# call: python /mnt/vstor/CSE_CSDS_VXC204/rxl761/anaconda3/envs/motus/bin/motus profile -f 11808.3069.SALB.W2V1.R1.fastq -r 11808.3069.SALB.W2V1.R2.fastq
#consensus_taxonomy	unnamed sample
Leptospira alexanderi [ref_mOTU_v31_00001]	0.0000000000
Leptospira weilii [ref_mOTU_v31_00002]	0.0000000000
Chryseobacterium sp. [ref_mOTU_v31_00004]	0.0000000000
Chryseobacterium gallinarum [ref_mOTU_v31_00005]	0.0000000000
Chryseobacterium indologenes [ref_mOTU_v31_00006]	0.0000000000
Chryseobacterium artocarpi/ureilyticum [ref_mOTU_v31_00007]	0.0000000000
Chryseobacterium jejuense [ref_mOTU_v31_00008]	0.0000000000
Chryseobacterium sp. G972 [ref_mOTU_v31_00009]	0.0000000000
Chryseobacterium contaminans [ref_mOTU_v31_00010]	0.0000000000
Chryseobacterium indologenes [ref_mOTU_v31_00011]	0.0000000000
Chryseobacterium arthrosphaerae [ref_mOTU_v31_00012]	0.0000000000
Chryseobacterium sp. [ref_mOTU_v31_00013]	0.0000000000
Chryseobacterium sp. YR459 [ref_mOTU_v31_00014]	0.0000000000
Chryseobacterium cucumeris/indologenes [ref_mOTU_v31_00015]	0.0000000000
Chryseobacterium sp. YR477 [ref_mOTU_v31_00016]	0.0000000000
Chryseobacterium sp. RU33C [ref_mOTU_v31_00017]	0.0000000000
Chryseobacterium gleum [ref_mOTU_v31_00018]	0.0000000000
Chryseobacterium culicis [ref_mOTU_v31_00019]	0.0000000000
Chryseobacterium joostei [ref_mOTU_v31_00020]	0.0000000000
Komagataeibacter xylinus/hansenii [ref_mOTU_v31_00021]	0.0000000000
Proteobacteria sp. [ref_mOTU_v31_00022]	0.0000000000
Sphingomonas sanguinis [ref_mOTU_v31_00023]	0.0000000000
Sphingomonas parapaucimobilis [ref_mOTU_v31_00024]	0.0000000000
Sphingomonas yabuuchiae [ref_mOTU_v31_00025]	0.0000000000
Vibrio natriegens [ref_mOTU_v31_00026]	0.0000000000
Vibrio sp. [ref_mOTU_v31_00027]	0.0000000000
Vibrio parahaemolyticus [ref_mOTU_v31_00028]	0.0000000000
Vibrio alginolyticus [ref_mOTU_v31_00029]	0.0000000000
Do you know what's going on here?

**Comment by hjruscheweyh** [comment]
Dear @lrt666 

the mOTUs profiles report by default relative abundances for all existing mOTUs (Just as if you would work with an OTU table). This means that most mOTUs will have a relative abundance of 0.0 and only a few (depending on the environment) mOTUs will have a relative abundance > 0.0.

Best,
Hans
