### ISSUE TITLE
GTDB Taxonomy for Version 3.1.0

### ISSUE THREAD

**Issue by G-Molano-LA** [motu-tool/mOTUs#123]
Hi,

Thanks for this great tool :) ! I couldn't find the GTDB taxonomy file for the version 3.1.0 which contains more ext-mOTUS annotated than version 3.0 (current GTDB file available). Could you please made it available?

I was also wondering if the database will be updated soon or so.

Best regards,

Alejandra

**Comment by Pluriscient** [comment]
See https://github.com/motu-tool/mOTUs/issues/120#issuecomment-1842678360
