### ISSUE TITLE
PIP releases miss the motus.remove.padded.sh file

### ISSUE THREAD

**Issue by d-goryslavets** [motu-tool/mOTUs#124]
Hello,

`motus snv_call` doesn't work when the package is installed with pip. The error is message is 
```
Error: metaSNVRMPadded finished with an error
Error: b'bash: /home/nepotlet/miniconda3/envs/motus-profiler-test/lib/python3.11/site-packages/motus/motus.remove.padded.sh: No such file or directory\n'
Error: b''
```
I get this error for all versions available on PyPi. When installed from source everything works fine.

**Comment by hjruscheweyh** [comment]
HI @d-goryslavets 

Thank you for making us aware of this issue. 

Hans
