### ISSUE TITLE
Error: Cannot call bwa on the file ERR4563329.fastq.gz

### ISSUE THREAD

**Issue by xiangjianmao** [motu-tool/mOTUs#125]
Error: bwa failed
Error: Cannot call bwa on the file ERR4563329.fastq.gz
![屏幕截图 2024-03-13 212311](https://github.com/motu-tool/mOTUs/assets/51312239/26fd5f50-1165-4a0c-8b1a-20c33dcdfe9e)

**Comment by Anto007** [comment]
I believe indexing your database fasta via bwa will make this error disappear

**Comment by hjruscheweyh** [comment]
Dear @xiangjianmao 

The database is downloaded as an indexed bwa database already. My guess is that the read file is corrupted or that bwa is not installed properly. Can you check with

```
gzip -t ERR...gz
bwa mem
```

and share the result.
