### ISSUE TITLE
Normalizing metagenomic gene relative abundance using MOTU2

### ISSUE THREAD

**Issue by Jigyasa3** [motu-tool/mOTUs#51]
Hey @AlessioMilanese 

I wanted to ask,  I am interested in quantifying gene-relative abundances from metagenomes using MOTU. For this, I have the RPKM counts (corrected for gene-length and read length) for extracted marker genes (from MOTU2 db) and annotated gene-families (from metagenomes). I wanted to ask:

a)Can I apply the transcriptome normalization method mentioned in the 2019 paper to metagenomes too?
b) If yes, then I am only interested in gene-family normalization regardless of taxonomy. Then do I just divide the RPKM of gene-family with the sum of RPKM for all MOTU per sample?
c) If I want to extract out taxa specific information, then I do the same as (b) but group the data for specific taxonomic rank?

Looking forward to your reply!

**Comment by AlessioMilanese** [comment]
Hi @Jigyasa3,

I think you refer to:
> To discern genomic potential from activity, the combined use of metagenomics with metatranscriptomics profiling is becoming increasingly popular. Here, we found that metatranscriptomic abundances of mOTUs are highly correlated with metagenomic abundances, which highlights the property of MGs as constitutively expressed housekeeping genes across different conditions. This suggests that mOTUs should be useful for normalizing metatranscriptomics data for differential gene expression analyses. Other methods depending on genes that are conditionally or variably expressed are demonstrably less suitable for this approach and may also give the misleading impression that many taxa are rare, but highly active, or abundant, but inactive or dead (Supplementary Figure 15).

What we mean is that the 10MGs have a steady expression, hence they measure "basal activity". So, in a metatranscriptomic sample, we expect to see something like:
```
marker gene 1
marker gene 1
marker gene 1
```

**Comment by AlessioMilanese** [comment]
I'm not sure how to apply this to metagenomic samples, or maybe I didn't understand the question?

**Comment by Jigyasa3** [comment]
Thank you for replying! I understand the basal expression part of the marker genes in the metagenomes. I am interested in using that concept for metagenomes too, and wanted to ask you if it would make sense. For example, I have the read count for the marker genes and my other functional genes. I am interested in doing a comparative analysis between functional genes, but as the data is compositional, any such correlations would be wrong. So I want to use the marker genes' read count data as a normalization factor for each functional gene count to be able to compare them. Does that make sense? Is it feasible?

**Comment by AlessioMilanese** [comment]
Ok, I understand!
I guess the following would work using the marker genes (MGs) and using `-c` to get read counts and not relative abundances. For each mOTU, you have to calculate:
```
------------- MOTU 1 -------------
      sample1   sample2   sample3
MG1        31      4782       257
...
MG10       31      4756       261
---
median     31      4739       259

------------- MOTU 2 -------------
      sample1   sample2   sample3
MG1       157        56       872
MG2       160        61       912
...
MG9       161        52       901
MG10      159        59       849
---
median    160        57       871
```
Now, the median is exactly what mOTUs is returning, if you use `motus profile`:
```
       sample1   sample2   sample3
mOTUs1      31      4739       259
mOTUs2     161        57       871
```

Now you can compare all the genes that comes from motus 1:
```
            sample1   sample2   sample3
mOTUs1           31      4739       259
-ABC_trans_1      0         1       519
-Kinesin_001     62      4760        51
```
and mOTUs2:
```
            sample1   sample2   sample3
mOTUs2           160        57       871
-Antipor_002      80        51      1700
```

And calculate abundances compared to that:
```
            sample1   sample2   sample3
mOTUs1            1         1         1
-ABC_trans_1      0    0.0001     2.001
-Kinesin_001      2      1.01     0.199
```
Where 2.001 for `ABC_trans_1` in `sample3` means that the gene `ABC_trans_1` appears on average 2 times more often than the marker genes (2 is from: 519/259). The marker genes are present in single copy in the genome. Hence, if you see 2 times more reads, I would expect that there are 2 copies of that genome.

Maybe to consider:
- how do you calculate the median if there are missing values? at the moment, for mOTUs I calculate the median of the genes that are different from zero.
- in a way you have to map the reads in the same way as you map to the marker genes
- what does 0.5 means? That there is half of the gene? I'm not sure how to interpret this.
