### ISSUE TITLE
Can I compare the fasta files to motus database?

### ISSUE THREAD

**Issue by zckoo007** [motu-tool/mOTUs#56]
Hi Alessio
I have a gene, I want to know which bacteria contain this gene. which is the right database for me to  comparison?
```
>FEFJLJPB_00126 S-adenosylmethionine synthase
ATGGGATACTTATTTACATCCGAATCGGTGTCAGAAGGACACCCCGACAAGGTAGCCGAT
CAAATATCGGATGCTGTGCTTGACAAACTGTTGGCTTACGACCCCAGTTCGAAAGTAGCT
TGCGAAACACTAGTGACTACCGGACAAGTGGTGCTAGCGGGTGAAGTGAAAACAAAAGCG
TACGTTGACCTCCAGCTCATCGCGCGCGAAGTGATTAAGAAAATCGGTTATACCAAAGGA
GAGTACATGTTCGAAAGTAACTCTTGTGGCGTACTTTCCGCTATTCATGAGCAAAGTCCT
GATATCAACCGTGGTGTAGAGCGTCAGGACCCGATGGAACAGGGTGCAGGCGACCAGGGT
ATGATGTTTGGCTACGCTACCAATGAAACGGAAAACTATATGCCGCTTTCTCTTGATCTG
GCACACCGCATTCTGCAAGTGCTGGCCGACATTCGTCGTGAAGGAAAGGTGATGACTTAC
CTCCGCCCCGATGCCAAAAGCCAGGTTACTATCGAATATGATGACAACGGAACTCCTGTT
CGCATCGATACAATCGTTGTTTCTACGCAACATGATGACTTTATCCAACCGGAAGATGAT
TCTCAAGCCGCCCAGCTGAAAGCTGACGAAGAAATGCTGTCTATCATCCGCCGTGATGTG
ATTGAAATTCTGATGCCTCGTGTCATTGCTTCTATCCATCACGATAAAGTGTTGGCACTG
TTTAATGATAAAATCATTTATCATGTGAATCCTACGGGCAAGTTCGTAATTGGTGGTCCT
CACGGAGATACCGGTTTGACAGGTCGTAAGATTATCGTTGATACTTATGGTGGTAAAGGT
GCTCACGGTGGTGGTGCTTTCTCCGGAAAAGATCCTAGCAAGGTAGACCGTAGTGCAGCT
TATGCAGCACGCCATATCGCAAAGAATATGGTTGCGGCAGGTGTAGCAGATGAAATGCTT
GTACAGGTGAGCTATGCTATCGGTGTGGCTCGTCCGATCAATATTTTTGTAGATACTTAT
GGCCGTTCCCACGTTAACATGACGGATGGTGAGATTGCCCGCGTTATCGATCAGTTGTTC
GATCTTCGCCCGAAAGCAATCGAAGAACGTCTGAAACTTCGTAATCCTATTTATCAGGAA
ACAGCCGCTTATGGTCACATGGGACGTGAACCGCAAGTGATAACGAAGAAGTTTTCTTCT
CGTTACGAAGGAGATAAAACAGTGGAAGTGGAACTCTTTACATGGGAGAAACTCGACTAC
GTAGATAAAATTAAAGCTGCTTTTGGTCTGTAA
```
![image](https://user-images.githubusercontent.com/25576334/91153816-4c506500-e6f3-11ea-92ab-becac8018390.png)

**Comment by AlessioMilanese** [comment]
Hi @zckoo007 ,
You can compare to `db_mOTU_DB_CEN.fasta` or `db_mOTU_DB_NR.fasta`.

`db_mOTU_DB_CEN.fasta` has one sequence per each marker gene per each mOTU. Since there are maximum 10 marker genes per mOTU, you expect to have maximum 10 sequences per mOTU.

`db_mOTU_DB_NR.fasta` has all non-redundant sequences for all mOTUs.

I would use `db_mOTU_DB_CEN.fasta`, since in the fasta header there is the mOTUs ID. Otherwise, for `db_mOTU_DB_NR.fasta` you need a map from genes to mOTUs. The map of genes to mOTUs can be found here:
https://zenodo.org/record/2635425#.X0Ti1ElS-50

**Comment by AlessioMilanese** [comment]
Note that you can have a meaningful map between your gene and the mOTUs genes, only if your query gene belong to one of the 10 gene families used in mOTUs.

By blasting your sequence, it has 100% identity to "Bacteroides ovatus strain 3725 D1 iv chromosome, complete genome". And _Bacteroides ovatus_ is in `ref_mOTU_v25_03475`.

Looking at `db_mOTU_taxonomy_ref-mOTUs.tsv`:
`Bacteroides sp. [Bacteroides sp. HMSC073E02/Bacteroides ovatus/Bacteroides xylanisolvens/Bacteroides sp. 1_1_30/Bacteroides sp. 3_1_13/Bacteroides sp. 3_1_23/Bacteroides sp. 2_1_22/Bacteroides sp. 2_2_4/Bacteroides sp. D1/Bacteroides sp. D2/Bacteroides sp. D22/Bacteroides fragilis]
`
