### ISSUE TITLE
Only zeros in abundance result

### ISSUE THREAD

**Issue by pavelmedina** [motu-tool/mOTUs#58]
Hi everyone,

I am Pavel from Mexico. I am working with metagenomic data trying to infer abundance in a sample of water (https://www.ebi.ac.uk/ena/browser/view/SRX7913461). I am using you software, mOTUs, but I have a problem that I do not understand. Each time I run the analysis, I get the same result with only cero values in abundance. It there exist an apparent error that I am omitting in my analysis that produce this kind o error?, Can you help me with this problem?

I attach my result.

Thanks, a lot.

[test1.motus.zip](https://github.com/motu-tool/mOTUs_v2/files/5256582/test1.motus.zip)

**Comment by AlessioMilanese** [comment]
Hi,
Thanks for your interest in mOTUs!

I see there are some different from zero:
```
Erythrobacter sp. [ref_mOTU_v25_05192]	0.1348728676
Methanohalophilus mahii [ref_mOTU_v25_05466]	0.1029955787
Coleofasciculus chthonoplastes [ref_mOTU_v25_07279]	0.7354934614
-1	0.0266380923
```

But just few. Can you have a look at this:
https://github.com/motu-tool/mOTUs_v2/wiki/FAQ#1-why-just-few-reads-map-in-my-profiles

If `-c` and decreasing `-l` and decreasing `-g` doesn't work, we can have a look at the profile!

**Comment by AlessioMilanese** [comment]
It can also be that the species in your sample are not represented in mOTUs.

**Comment by pavelmedina** [comment]
Ok, let me try this. I will notify you the results in a couple of hours.

Thanks.
