### ISSUE TITLE
metaSNV results is empty

### ISSUE THREAD

**Issue by taylorreiter** [motu-tool/mOTUs#59]
Hello,

I successfully ran mOTU using the following code:

```
conda create -n motus motus
conda activate motus
for infile in metagenome_reads/*fq.gz
do
    bn=$(basename ${infile} .fq.gz)
    echo "Running motus on ${bn}"
    motus map_snv -s ${infile} -t 8 > map_snv_out/${bn}.bam
done

motus snv_call -d map_snv_out -o snv_call_out
```
However, the run ended with:
```
[W::main] The result is empty
[main] End metaSNV
```

I'm curious what can cause this to happen. 

Running `ls -lah` on the `snv_call_out` directory, I see:

```
total 13M
drwxr-xr-x 4 tereiter tereiter   7 Sep 26 20:20 .
drwxr-xr-x 5 tereiter tereiter   7 Sep 26 20:13 ..
drwxr-xr-x 2 tereiter tereiter   2 Sep 26 20:20 distances-m2-d5-b80-c5-p0.9
drwxr-xr-x 2 tereiter tereiter   2 Sep 26 20:20 filtered-m2-d5-b80-c5-p0.9
-rw-r--r-- 1 tereiter tereiter 83K Sep 26 20:20 metaSNV.log
-rw-r--r-- 1 tereiter tereiter 68M Sep 26 20:18 snv_call_out.all_cov.tab
-rw-r--r-- 1 tereiter tereiter 68M Sep 26 20:18 snv_call_out.all_perc.tab
```

Is there actually not enough information in my reads to run metaSNV, or did something else occur?

I have the following versions installed:
```
metasnv                   1.0.3                h230ddbb_2    bioconda
motus                     2.5.1                      py_0    bioconda
```

And I'm attaching the log file here. Note my files end in `.fa.gz`, but they're actually fastq files. 
[metaSNV.log](https://github.com/motu-tool/mOTUs_v2/files/5293533/metaSNV.log)

**Comment by LucasPaoli** [comment]
Hi Taylor,

It does look like none of the mOTUs went through the metaSNV filtering parameters. Here you would be looking for 'species' that have at least 80% horizontal coverage (-b) and 5X vertical coverage (-d) in two or more samples (-m). 

This could be the case for two reasons: either the ecosystem you're working with is not well represented in the current mOTUs database (we're working on extending the db to tackle this issue) and/or the metagenomes are not very deeply sequenced, making it more difficult to go through the thresholds.

What I would suggest it to look into the snv_call_out.all_cov.tab and snv_call_out.all_perc.tab files to check the vertical coverages (cov.tab) and horizontal coverage (perc.tab). Based on that you may be able to change the filtering parameters to better fit your data. However, the way the SNVs are called does need a minimum coverage at a given position and there is no way around that.

Hope that helps,

Lucas

**Comment by taylorreiter** [comment]
Thank you @LucasPaoli! This helps me develop and intuition for vertical/horizontal coverages and adjusting the filtering parameters as necessary.
