### ISSUE TITLE
OTU clustering/distance matrix of marker-genes from different samples

### ISSUE THREAD

**Issue by Jigyasa3** [motu-tool/mOTUs#65]
Hey @AlessioMilanese 

I am interested in clustering marker-genes from 4 different samples into OTUs and getting a distance matrix to understand how similar two samples are to each other based on marker-gene data (similar to [Supplementary figure 13](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-019-08844-4/MediaObjects/41467_2019_8844_MOESM1_ESM.pdf) of the 2019 paper)

I am following the methods section whereby `usearch usearch-global` method was used to get pairwise comparisons. But unfortunately, my marker-gene data is very distant from the mOTU2 database. I get an empty output file with default parameters. Any suggestions on this?

**Comment by AlessioMilanese** [comment]
Hi @Jigyasa3,

I think you are looking at the wrong part of the methos: `usearch usearch_global` was used to cluster the 16S amplicon data and not for mOTUs (Figure 3). The section immediately after that refers to supplementary figure 13:
>Between sample distances were determined using human body site samples for which more than one time point was available for the same individual. More specifically, for each body site, we compared community compositional distances between samples from the same individual (intra-individual) to distances between this and other individuals (inter-individual). Canberra and Bray-Curtis distances were computed with the vegdist R function of the vegan package and the log-Euclidean distance was computed as the Euclidean distance of the log-transformed relative abundances after the addition of a pseudocount smaller than the smallest non-zero value. For each of the three distances and each sample, we identified the most similar sample (i.e. the one with the minimum distance value) and determined the proportion of cases in which both samples belonged to the same individual.

Supplementary figure 13 is based on taxonomic profiles and not on distances between genes.
I would run mOTUs on the 4 samples, in this way you obtain 4 taxonomic profiles. You can then use these profiles to calculate measures of beta diversity as in supplementary figure 13.
