### ISSUE TITLE
Ileibacterium appears twice in mOTU v2.6.1

### ISSUE THREAD

**Issue by metaganal** [motu-tool/mOTUs#71]
Hi, I want to report a bug in mOTUs v2.6.1.

Ileibacterium appears twice when annotating short reads at the genus level.
Identical bug has been reported previously(#61) and it seems that release 2.6 solved it, but it reappears in release 2.6.1

After checking the database that mOTU downloaded by setup.py (specifically db_mOTU_taxonomy_ref-mOTUs.tsv), I can see that ref_mOTU_v25_10239 is annotated as 1980680 Ileibacterium, while ref_mOTU_v25_05939 is annotated as 1937007 Ileibacterium, causing duplicate of Ileibacterium as IDs are removed in the resulting profile.

Should I just use release 2.6 in the meantime?

**Comment by AlessioMilanese** [comment]
Hi @metaganal ,

Thanks for pointing that out, we will fix with the next version. This came back in after solving https://github.com/motu-tool/mOTUs/issues/45 .

> Should I just use release 2.6 in the meantime?

For now yes. I'll write here when we solve with the new version.

**Comment by AlessioMilanese** [comment]
Solved with 3.0.1
