### ISSUE TITLE
question about isolate sequencing data

### ISSUE THREAD

**Issue by franciscozorrilla** [motu-tool/mOTUs#75]
Hi, I was wondering if `mOTUs2` was tested on isolate sequencing data? 
Does it make sense to use this tool for assesing quality/contamination of isolates short read sequencing files?

Thanks,
Francisco

**Comment by AlessioMilanese** [comment]
Hi @franciscozorrilla,

We did not test it directly, but we actually use it also for that.

Also compare the relative abundances. For example, if you are sequencing a E.coli isolate and profile 0.99 relative abundance of E.coli, then it should be fine. If 0.3 of the relative abundance is _Staphylococcus epidermidis_ you might have a contamination.

**Comment by franciscozorrilla** [comment]
I see, thanks for the info! This is what 9 of my soil-derived isolate samples look like in my analysis:

![image](https://user-images.githubusercontent.com/35606471/126992735-29170fbf-4d23-4568-86c0-7905c8bd169e.png)

So the sample in the top right corner is probably trustworthy isolate, whereas the one in the top middle might be contaminated (or consists of co-dependent bacteria)?

**Comment by AlessioMilanese** [comment]
That is what mOTUs would suggest. What you can do is to compare contigs to Bacterial genomes and see if there is a similar message also there.
