### ISSUE TITLE
Error with append.py

### ISSUE THREAD

**Issue by Alexey-Kovtun** [motu-tool/mOTUs#77]
Hi!

I've installed the latest version of mOTUs and got an error while trying to run the program:

Error: fail to load the script: /mnt/lustre/kovtunas/miniconda3/share/motus-3.0.1/bin/append.py
Download the motus profiler again

I tried two variants of installation: the one specified in the "Installation" section and through conda. Both give me the same error.

I've tried installing mOTUs before (the older versions, don't remember which ones) on another server and everything worked just fine.

Please, help! Thank you!

**Comment by AlessioMilanese** [comment]
Hi @Alexey-Kovtun ,

Thanks for your interest in mOTus.

That sounds weird. I just tried now and it works fine for me with both `-i` and `-d`.

Which version of python are you using? (you can check also with `motus --version`)

What command are you using? Can you try to run with `-v 10`

**Comment by Alexey-Kovtun** [comment]
Thank you for a quick reply!
Good to hear that it actually works. There are difficulties with this particular server. It has Python as modules + I have conda installed.
When installing with basic installation, I switched conda off (so it does not conflict) and turned Python3 v 3.8.2 on.
I guess now that I'll have to 'play' with switching the modules on/off. Maybe that'll give the result.

On another server older version of mOTUs works fine.

**Comment by AlessioMilanese** [comment]
I see. Maybe you can run `motus merge` in another machine. That's maybe not an ideal solution, but the profiles are quite small in size and merging would work also on a normal laptop.

**Comment by Alexey-Kovtun** [comment]
Yeah, I'm analyzing a dataset, so I might need it (instead of inventing my own scripts).

Yeah, since we're talking this through, I'm also wondering, what type of normalization for the taxonomy counts would you recommend in order to run comparison tests between the datasets (like case/control comparison)? Correct me, if I'm wrong, but it seemed to me that you hadn't built in any normalization for the readcounts (like, for example, in MetaPhlAn). And simply dividing by the overall number of assigned reads is not actually the most precise strategy.

**Comment by AlessioMilanese** [comment]
I would use the default `-y insert.scaled_counts` which normalise for different gene/genome size. This gives the best results. In an independent evaluations of many profilers, mOTUs results on top:
https://www.nature.com/articles/s41596-020-00480-3
(see Figure 7)

From this, there are many normalizations that you can use to test associations in case/control studies. For example: calculate relative abundance, use log values, rarefy, and others. Have a look at SIAMCAT:
https://siamcat.embl.de/

It's doing exactly what you want (going from raw read counts to association testing and model prediction). An application of SIAMCAT on mOTUs profiles for a case/control (colorectal cancer VS healthy) study:
[Wirbel et al. Nature Medicine 2019](https://www.nature.com/articles/s41591-019-0406-6)

**Comment by Alexey-Kovtun** [comment]
Oh, this is very helpful! Thank you very much!
