### ISSUE TITLE
Conda motus-3.0.1

### ISSUE THREAD

**Issue by plmeta** [motu-tool/mOTUs#78]
Hello,

I wonder if conda install is working now for version 3.0.1. I saw the package is already on conda. But it still installs version 1.0 when using it.

Thanks!

All the best,
pl

**Comment by AlessioMilanese** [comment]
Hello,

That's weird. Can you try to run:
```
 conda install -c bioconda/label/cf201901 motus 
```

**Comment by plmeta** [comment]
Hi, thanks for the quick reply. I think I found the issue. I am installing with a .yml file and there are some dependencies that forced motus to install a lower version.

**Comment by AlessioMilanese** [comment]
I see. i guess samtools or bwa, or maybe something related to metaSNV.
Is it working now?

**Comment by plmeta** [comment]
I haven't unfortunately. I managed to install 3.0.1 once but now I couldn't manage again. It is now version 2.0.1 with dependencies like blow. I tried also both py3.7 and py3.8.
![Screenshot 2021-08-10 at 15 36 03](https://user-images.githubusercontent.com/65559394/128876853-0fa7d606-41bf-40e8-8a27-fadab204caa5.png)

**Comment by AlessioMilanese** [comment]
maybe create a new conda environment can help?
https://github.com/motu-tool/mOTUs/wiki/Installation#install-dependencies-with-conda

**Comment by plmeta** [comment]
Hi, finnally I made it to work.

python 3.8.1 + samtools 1.9 + bwa 0.1.17, then I am getting motus 3.0.1 by: 
conda install -c bioconda motus=3.0.1

**Comment by AlessioMilanese** [comment]
Nice!

I know it can be messy with the different tool versions, and it's not completely under our control.
Thanks for cheking. I can point to this discussion if anyone gets the same problem!
