### ISSUE TITLE
Map file for v3 database

### ISSUE THREAD

**Issue by trickovicmatija** [motu-tool/mOTUs#82]
Hey,
First of all, nice tool!
I have found the file on Zenodo (https://zenodo.org/record/2635425#.YaAHgC2ZPy9) with information how to map genes to mOTU names. I am interested if you want to share that same file, but for v3 database?

Thanks,
Matija

**Comment by AlessioMilanese** [comment]
It's available now.
Cheers,
alessio

**Comment by trickovicmatija** [comment]
Thank you very much!

Best,
Matija
