### ISSUE TITLE
Database Extension

### ISSUE THREAD

**Issue by Jibowe** [motu-tool/mOTUs#84]
Hi，
I am trying to add my own genomes to the database and using extend_mOTUs_DBv2.5 and mOTUs v3.0.1. But I had the same problem. I can't run the script extend_mOTUs_addGenome.sh successfully because the file db_mOTU_DB_NR.fasta.udb was not found in the db folder.
Thanks for your help!

**Comment by Franz2022** [comment]
I have the same problem. Please, what do we do wrong?

**Comment by AlessioMilanese** [comment]
We updated and improved the extender scripts, now they are available here:
https://github.com/motu-tool/mOTUs-extender
