### ISSUE TITLE
Pypi package `motus` is something else, instructions outdated

### ISSUE THREAD

**Issue by gromain** [motu-tool/mOTUs#88]
Hello,

I'm trying to run motus in an environment where Conda is not supported.

While trying to setup a new machine using your instructions, it appears there already is a [motus package](https://pypi.org/project/motus/#description) in Pypi, except it's not this one!

Instructions on the website at https://motu-tool.org/installation.html don't work anymore either.
More specifically, the commands given are broken and the repository outdated (but it stills redirect to this one, so that's a win!). One should do `python setup.py install` to install properly mOTUs.

Also, since dependencies are not managed properly this way, is it possible to both update the docker image and host it on hub.docker.com (quay.io forces to register to download an image, which is both inconvenient and not privacy friendly) ? This way I would be able to pull it as a [singularity image](https://sylabs.io/guides/3.5/user-guide/singularity_and_docker.html#).
Or even better, build a singularity image and spread the love! ;-)
I can help with the singularity image building, I just need the Dockerfile that was used to build the docker image.

Happy to help where I can!

**Comment by gromain** [comment]
Also, the `test.py` is broken (because of the broken `setup.py`).

:-)

**Comment by AlessioMilanese** [comment]
Hi @gromain 
We were in the porcess of updating mOTUs and adding it to pip when we realised that the name was already in use. We found now an alternative and updated the website.

**Comment by AlessioMilanese** [comment]
Also, thanks for reporting the issue, we are always keen on improving!
For the docker image, I would wait a few days that we will have an updated database.
