### ISSUE TITLE
no unassigned with full taxonomy

### ISSUE THREAD

**Issue by gitcat01** [motu-tool/mOTUs#89]
Hi,

I was using mOTU on marine metagenomes and it works great!
However, I used flags -A -c to report counts and full taxonomy but then I don't receive number of unassigned reads. Is there a way to receive counts, full taxonomy and unassigned reads?

Thank you very much!

**Comment by AlessioMilanese** [comment]
Hi,

> I was using mOTU on marine metagenomes and it works great!

Nice to hear!

> However, I used flags -A -c to report counts and full taxonomy but then I don't receive number of unassigned reads.

Unfortunately the output format with `-A` is designed not to have `unassigned`. You need to run mOTUs two times to find this information. The first time you run it, you can save the intermediate MGC count with `-M` so that the second run is much faster. For example:

```bash
motus profile -s db_mOTU/db_mOTU_test/test1_single.fastq -A -c -M temp.mgc  > res_temp
motus profile -c -m temp.mgc | grep -P "unassigned\t" > res_temp2
cat res_temp res_temp2 > RESULT
```
