### ISSUE TITLE
Error extending mOTU 2.5.1 database

### ISSUE THREAD

**Issue by Xentrics** [motu-tool/mOTUs#91]
I try to follow the instruction on [Extending_the_mOTUs_database](file:///home/basti/.cache/.fr-oQD27y/extend_mOTUs_DBv2.5/Extending_the_mOTUs_database.html). I proceeded creating the conda environment and downloaded the mOTU 2.5.1 database (and moved it into the mOTU folder).

I am trying to run the test genomes, but I experience a crash. The pipeline _starts_ successfully until it tries to create the GFF using **runMakePaddedMG_DB**.
The errors says:

>   File "extend_mOTUs_DB/SCRIPTS//makePaddedMGdb.py", line 413, in runMakePaddedMG_DB
    getPaddedSequences(extractLocationsFileName, contigsFasta, paddedFastaFileName, dictExtractName2writeName)
  File "extend_mOTUs_DB/SCRIPTS//makePaddedMGdb.py", line 312, in getPaddedSequences
    if (line.startswith('>')):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

I noticed that in the **extend_mOTUs_addGenome.sh** script, the python code is started using **python2**, which is indeed not present in the conda environment (it uses python 3.6.5).

Is this a python version error? Or is this a setup issue?

**Comment by AlessioMilanese** [comment]
It seems it's opening the file in bytes mode, and so it's calling `bytes.startswith()` and not `str.startswith()`.

>I noticed that in the extend_mOTUs_addGenome.sh script, the python code is started using python2, which is indeed not present in the conda environment (it uses python 3.6.5).
>Is this a python version error? Or is this a setup issue?

We don't support python 3 anymore. If you are using python 2, that might be the issue.

@hjruscheweyh did you see this before?

**Comment by Xentrics** [comment]
Just for completeness sake: no, I used python 3.6.5.
It also appear with any of the test genomes (and the 3 additional ones that I try to add).

Could this be an issue with the reference database? I got the 2.5.1 database from [https://zenodo.org/record/3366460#.YnzBY2pBxB8](zendo). I will try 2.5.0 in the meantime, just to check.

**Comment by AlessioMilanese** [comment]
Can you post here the call that you do?

**Comment by AlessioMilanese** [comment]
From the issue you get, it seems you are working on a gzip file. The problematic function is this:
```python
def getPaddedSequences(extractLocationsFileName, contigsFasta, paddedFastaFileName, dictExtractName2writeName): 

	paddedFastaFile = open(paddedFastaFileName, "w")

	cat = subprocess.Popen(['cat', extractLocationsFileName], 
							stdout=subprocess.PIPE,
							)

	samtools = subprocess.Popen(['xargs', 'samtools', 'faidx', contigsFasta],
							stdin=cat.stdout,
							stdout=subprocess.PIPE,
							)
							
	output = samtools.stdout

	for line in output:
		if (line.startswith('>')):  #  <------------------------------------------- ISSUE HERE
			line = line.strip()
			recordName = line.replace('>', '')
			newRecordName = dictExtractName2writeName[recordName].pop()
			newRecordName = newRecordName.strip()
			paddedFastaFile.write(">" + newRecordName + "\n")
		else:
			paddedFastaFile.write(line)
```

You could try to change the code in `extend_mOTUs_DB/SCRIPTS//makePaddedMGdb.py` at line 312, and add `line = line.decode("utf-8")`. Like:

```python
	for line in output:
                line = line.decode("utf-8")  #  <--------------------------------- ADDED LINE
		if (line.startswith('>')):  #  <------------------------------------------- ISSUE HERE
```

But it might be that there is a another problem underneath. Maybe with samtools? (since `output = samtools.stdout`)

**Comment by Xentrics** [comment]
YES! That worked. I will check the rest of the test script, for completeness sake. But the script finished without further issue :)
