### ISSUE TITLE
list of taxa present in the mOTUs database? 

### ISSUE THREAD

**Issue by rjsorr** [motu-tool/mOTUs#93]
Hi, can you provide a link to the taxa included in the mOTUs database?
I'm considering using this tool, but before I use time downloading, installing, learning, running and interpreting I would like to know if it suits my goal? Basically I want to classify my reads to the superkingdom/kingdom level before focusing on bacteria, so simply % eukaryotes, virus, Archaea and Bacteria would be desired. But will mOTU work for this and give a realistic representation of the diversity without database bias? and if so, how would you go forward to do this? 

regards

**Comment by AlessioMilanese** [comment]
Hi,
mOTUs can profile Archaea and Bacteria.

For the list of all clades check:
https://github.com/motu-tool/mOTUs/wiki/FAQ#4-where-can-i-find-the-taxonomy-annotation-for-each-motus

or if you can use R:
https://github.com/AlessioMilanese/motus_taxonomy
(`load(url("https://github.com/AlessioMilanese/motus_taxonomy/blob/master/data/motus_taxonomy_3.0.1.Rdata?raw=true"))`)
