### ISSUE TITLE
GTDB mOTUs taxonomy ?

### ISSUE THREAD

**Issue by tapj** [motu-tool/mOTUs#95]
Hi,

Is there any plan to propose GTDB as alternative taxonomy to mOTUs?
if not, what would be your advice for generating GTDB taxonomy for mOTUs?

thank you,

Julien

**Comment by AlessioMilanese** [comment]
Hi Julien,

Thanks for your interest!
We are working on it, but it will take a bit. We are currently annotating all genomes that were used to build mOTUs 3 with the latest version of GTDB-Tk. I will keep you updated!

Once we have the annotation, I could provide you the GTDB annotation for the mOTUs before we actually implement it in the code.

Best,
alessio

**Comment by AlessioMilanese** [comment]
Please have a look here: https://github.com/motu-tool/mOTUs/wiki/GTDB-taxonomy-for-the-mOTUs

**Comment by tapj** [comment]
Hi Alessio,

That's awsome, I am sure that other mOTU users will find it useful too.

I will use it for the following weeks and keep you updated if I find some issues.

Thank you very much,

Julien
