### ISSUE TITLE
I want to know where the database is downloaded and installed.

### ISSUE THREAD

**Issue by luozhy88** [motu-tool/mOTUs#96]
I want to know where the database is downloaded and installed.
![image](https://user-images.githubusercontent.com/94740863/190292889-84622f99-23d6-4875-b345-94c9c0cfefb3.png)

**Comment by hjruscheweyh** [comment]
Hi @luozhy88 

mOTUs is installed as a python package into one of the `site-packages` folders - The exact location depends on the exact `pip` command. The database is in the subfolder of the mOTUs package folder.

Here is the command to find the location of the `site-packages`

```
python -m site
```

Best,
Hans

**Comment by luozhy88** [comment]
good,Thanks!
