### ISSUE TITLE
missing GTDB classification for motus_3 ids

### ISSUE THREAD

**Issue by TianyiChang** [motu-tool/mOTUs#97]
Hi there

Thanks for providing a GTDB annotation file. It seems that many motus were missing from 'mOTUs_3.0.0_GTDB_tax.tsv', such as the below:

meta_mOTU_v3_13058
meta_mOTU_v3_13316
meta_mOTU_v3_13553
meta_mOTU_v3_13666
meta_mOTU_v3_13677
meta_mOTU_v3_13799
meta_mOTU_v3_14519

I was wondering if there are quality issues associated with these missing motus?

Thanks!

**Comment by AlessioMilanese** [comment]
This meta-mOTUs have no genome or MAG, hence it was not possible to run GTDB-Tk.

I will fix the taxonomy next week (but basically for these there is no GTDB annotation).

**Comment by TianyiChang** [comment]
Thank you so much for your quick reply! It seems a bit strange since some of my query genomes were assigned to these meta-mOTUs (there are 84 mOTUs in total in my case), which have no GTDB taxonomy information.
  
​
  
​I look forward to hearing back from you.
  
​
  
​Thanks again.
  
​

**Comment by AlessioMilanese** [comment]
The file it's updated now. We also added the GTDB annotation for each genome: https://zenodo.org/record/7146984#.Y0XdplJBwbk

**Comment by TianyiChang** [comment]
Thanks a lot!!
  
​
