### ISSUE TITLE
Incomplete species annotation in the GTDB file?

### ISSUE THREAD

**Issue by cotillau** [motu-tool/mOTUs#98]
Hello Alessio,

Thank you so much for providing the GTDB mOTUs annotation file. There is something I do not understand about species annotation. There are, as you explain, some Not_annotated or Incongruent species, but all the others appear in the file to be the same as the genus (ie. missing the second part of the name). For example for ref_mOTU_v3_00001, we have:

ref_mOTU_v3_00001	d__Bacteria	p__Spirochaetota	c__Leptospirae	o__Leptospirales	f__Leptospiraceae	g__Leptospira	s__Leptospira

Am I missing something?

Thanks!

**Comment by AlessioMilanese** [comment]
There was an error when I updated the file. It is solved now.

Thanks for reporting!
Cheers,
alessio

**Comment by AlessioMilanese** [comment]
FYI. We provide also the GTDB annotation for each genome at: https://zenodo.org/record/7146984#.Y0XdplJBwbk
